# To be run in git-bash on Windows
set default-list
set dotenv-path := 'metadata.env'

# Ninja version parts
export NBASE := `echo "$NINJAMIN" | cut -d. -f1`
export NMAJOR := `echo "$NINJAMIN" | cut -d. -f2`
export NMINOR := `echo "$NINJAMIN" | cut -d. -f3`

# Commands
NSIS := env('NSIS_MAKE', 'makensis')
VDFS := env('GOTHIC_VDFS', 'gothicvdfs -b')

# Clean build directory
clean:
    rm -rf build

# Build VDF (release or dev)
[arg('TARGET', pattern="(dev|release)")]
build TARGET='dev': _populate_version
    mkdir -p build/{{ TARGET }}
    find src -type f -exec attrib -a -h -r -s {} \;
    @echo "{{ replace(VM_PRELUDE, '@TARGET@', TARGET) + read('src' / env('PATCHNAME') + '.vm') }}" > tmp.vm
    @{{ if TARGET == 'release' { 'echo "' + replace(read('tmp.vm'), 'placeholder', VM_EXCLUDE) + '" > tmp.vm' } else { '' } }}
    {{ VDFS }} ./tmp.vm
    @-rm -rf tmp.vm

# Bundle release
bundle: (build 'release')
    @echo "{{ TOOL_CFG }}" > build/release/tool.cfg
    {{ NSIS }} -X"SetCompressor /FINAL lzma" setup/g1mod.nsi

# Bump version (base, major, minor)
[arg('WHICH', pattern="(base|major|minor)")]
[script]
bump WHICH:
    case {{ WHICH }} in
        minor)
            VMINOR=$(( $VMINOR + 1 ))
            ;;
        major)
            VMAJOR=$(( $VMAJOR + 1 ))
            VMINOR=0
            ;;
        base)
            VBASE=$(( $VBASE + 1 ))
            VMAJOR=0
            VMINOR=0
            ;;
    esac
    perl -i -pe "s/^VBASE=.*$/VBASE=$VBASE/" metadata.env
    perl -i -pe "s/^VMAJOR=.*$/VMAJOR=$VMAJOR/" metadata.env
    perl -i -pe "s/^VMINOR=.*$/VMINOR=$VMINOR/" metadata.env
    just _populate_version $VBASE $VMAJOR $VMINOR
    # Bump changelog
    ver=$VBASE.$VMAJOR.$VMINOR
    ver_id=$VBASE$VMAJOR$VMINOR
    changelogdate=$(date +"%Y-%m-%d")
    perl -i -pe "s/(^## \[Unreleased\]$)/\1\\n\\n### General\\n\\n### Story\\n\\n<a name=\"v$ver_id-$changelogdate\"><\/a>\\n\\n## [$ver] - $changelogdate/" CHANGELOG.md
    perl -i -pe "s/(^\[unreleased\]: https:\/\/g1cp.org\/compare\/).*$/\1v$ver...HEAD\\n[$ver]: https:\/\/g1cp.org\/releases\/tag\/v$ver/" CHANGELOG.md
    # Bump changelog DE
    perl -i -pe "s/(^## \[Unreleased\]$)/\1\\n\\n### General\\n\\n### Story\\n\\n<a name=\"v$ver_id-$changelogdate\"><\/a>\\n\\n## [$ver] - $changelogdate/" docs/changelog_de.md
    perl -i -pe "s/(^\[unreleased\]: https:\/\/g1cp.org\/compare\/).*$/\1v$ver...HEAD\\n[$ver]: https:\/\/g1cp.org\/releases\/tag\/v$ver/" docs/changelog_de.md

# Populate metadata in Daedalus
_populate_version $VBASE=env('VBASE') $VMAJOR=env('VMAJOR') $VMINOR=env('VMINOR'):
    @echo "{{ VERSION_FILE }}" | sed 's/$/\r/' > {{ 'src' / 'Ninja' / env('PATCHNAME') / 'Content' / "version.d" }}

# Spine configuration
TOOL_CFG := '''
; Dependencies Spine, see https://clockwork-origins.com/spine-tutorial-tool-cfg
[DEPENDENCIES]
Required=\"314,613\"'''

# Daedalus version info
VERSION_FILE := '''
/* This file is automatically generated. Do not edit */
const int G1CP_Version = $VBASE*10000+$VMAJOR*100+$VMINOR;
const int G1CP_NinjaMinVer = $NBASE*1000+$NMAJOR*100+$NMINOR;
const string G1CP_NinjaMinVerStr = \"$NINJAMIN\";'''

# VDF metadata
VM_PRELUDE := '''
[BEGINVDF]
Comment=$LONGNAME  $VBASE.$VMAJOR.$VMINOR%%N$WEBSITE
BaseDir=src
VDFName=build/@TARGET@/$PATCHNAME.vdf
;'''

# Testsuite is excluded in release build
VM_EXCLUDE := '''
Ninja\\\$PATCHNAME\\Content\\Tests* -r
Ninja\\\\$PATCHNAME\\Tests* -r'''
