# To be run in git-bash on Windows
set default-list
set dotenv-path := 'metadata.env'

# Ninja version parts
export NMAJOR := `echo "$NINJA_VERSION_MIN" | cut -d. -f1`
export NMINOR := `echo "$NINJA_VERSION_MIN" | cut -d. -f2`
export NPATCH := `echo "$NINJA_VERSION_MIN" | cut -d. -f3`

# Commands
NSIS := env('NSIS_MAKE', 'makensis')
VDFS := env('GOTHIC_VDFS', 'gothicvdfs -b')

# Clean build directory
clean:
    rm -rf build

# Build VDF (release or dev)
[arg('TARGET', pattern="(dev|release)")]
build TARGET='dev': _populate_version
    mkdir -p build/{{ TARGET }}
    find src -type f -exec attrib -a -h -r -s {} \;
    @echo "{{ replace(VM_PRELUDE, '@TARGET@', TARGET) + read('src' / env('PROJECT_SLUG') + '.vm') }}" > tmp.vm
    @{{ if TARGET == 'release' { 'echo "' + replace(read('tmp.vm'), 'placeholder', VM_EXCLUDE) + '" > tmp.vm' } else { '' } }}
    {{ VDFS }} ./tmp.vm
    @-rm -rf tmp.vm

# Bundle release
bundle: (build 'release')
    @echo "{{ TOOL_CFG }}" > build/release/tool.cfg
    {{ NSIS }} -X"SetCompressor /FINAL lzma" setup/g1mod.nsi

# Bump version (major, minor, patch)
[arg('WHICH', pattern="(major|minor|patch)")]
[script]
bump WHICH:
    case {{ WHICH }} in
        patch)
            VERSION_PATCH=$(( $VERSION_PATCH + 1 ))
            ;;
        minor)
            VERSION_MINOR=$(( $VERSION_MINOR + 1 ))
            VERSION_PATCH=0
            ;;
        major)
            VERSION_MAJOR=$(( $VERSION_MAJOR + 1 ))
            VERSION_MINOR=0
            VERSION_PATCH=0
            ;;
    esac
    echo "Bump version to $VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH"
    perl -i -pe "s/^VERSION_MAJOR=.*$/VERSION_MAJOR=$VERSION_MAJOR/" metadata.env
    perl -i -pe "s/^VERSION_MINOR=.*$/VERSION_MINOR=$VERSION_MINOR/" metadata.env
    perl -i -pe "s/^VERSION_PATCH=.*$/VERSION_PATCH=$VERSION_PATCH/" metadata.env
    just _populate_version $VERSION_MAJOR $VERSION_MINOR $VERSION_PATCH
    # Bump changelog
    ver=$VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH
    ver_id=$VERSION_MAJOR$VERSION_MINOR$VERSION_PATCH
    changelogdate=$(date +"%Y-%m-%d")
    perl -i -pe "s/(^## \[Unreleased\]$)/\1\\n\\n### General\\n\\n### Story\\n\\n<a name=\"v$ver_id-$changelogdate\"><\/a>\\n\\n## [$ver] - $changelogdate/" CHANGELOG.md
    perl -i -pe "s/(^\[unreleased\]: https:\/\/g1cp.org\/compare\/).*$/\1v$ver...HEAD\\n[$ver]: https:\/\/g1cp.org\/releases\/tag\/v$ver/" CHANGELOG.md
    # Bump changelog DE
    perl -i -pe "s/(^## \[Unreleased\]$)/\1\\n\\n### General\\n\\n### Story\\n\\n<a name=\"v$ver_id-$changelogdate\"><\/a>\\n\\n## [$ver] - $changelogdate/" docs/changelog_de.md
    perl -i -pe "s/(^\[unreleased\]: https:\/\/g1cp.org\/compare\/).*$/\1v$ver...HEAD\\n[$ver]: https:\/\/g1cp.org\/releases\/tag\/v$ver/" docs/changelog_de.md

# Populate metadata in Daedalus
_populate_version $VERSION_MAJOR=env('VERSION_MAJOR') $VERSION_MINOR=env('VERSION_MINOR') $VERSION_PATCH=env('VERSION_PATCH'):
    @echo "{{ VERSION_FILE }}" | sed 's/$/\r/' > {{ 'src' / 'Ninja' / env('PROJECT_SLUG') / 'Content' / "version.d" }}

# Spine configuration
TOOL_CFG := '''
; Dependencies Spine, see https://clockwork-origins.com/spine-tutorial-tool-cfg
[DEPENDENCIES]
Required=\"$SPINE_DEPENDENCIES\"'''

# Daedalus version info
VERSION_FILE := '''
/* This file is automatically generated. Do not edit */
const int G1CP_Version = $VERSION_MAJOR*10000+$VERSION_MINOR*100+$VERSION_PATCH;
const int G1CP_NinjaMinVer = $NMAJOR*1000+$NMINOR*100+$NPATCH;
const string G1CP_NinjaMinVerStr = \"$NINJA_VERSION_MIN\";'''

# VDF metadata
VM_PRELUDE := '''
[BEGINVDF]
Comment=$PROJECT_NAME  $VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH%%N$WEBSITE
BaseDir=src
VDFName=build/@TARGET@/$PROJECT_SLUG.vdf
;'''

# Testsuite is excluded in release build
VM_EXCLUDE := '''
Ninja\\\$PROJECT_SLUG\\Testsuite.src
Ninja\\\$PROJECT_SLUG\\Content\\Tests* -r'''
