# Platform specific definitions
ifdef OS
	RM 			:=	del /Q /S
	FixPath		 =	$(subst /,\,$1)
	mkdir		 =	mkdir $(subst /,\,$(1)) > nul 2>&1 || (exit 0)
	mv			 =	rename $(subst /,\,$(1)) $(subst /,\,$(2))
	rwildcard	 =	$(foreach d,$(wildcard $(1:=/*)),$(call rwildcard,$d,$2) $(filter $(subst *,%,$2),$d))
else ifeq ($(shell uname), Linux)
	ERR			 =	$(error 'Linux not supported')
	RM			 =	$(ERR)
	FixPath		 =	$(ERR)
	mkdir		 =	$(ERR)
	mv			 =	$(ERR)
	rwildcard	 =	$(ERR)
endif

# Meta data
META			:=	metadata.txt

# Include meta data
include $(META)
export VERSION=$(VBASE).$(VMAJOR).$(VMINOR)

# Flags
VERBOSE			:=	0
DEVSETUP		:=	0
BT_RELEASE		:=	release
BT_DEVELOP		:=	dev
BUILDTYPE		 =	$(BT_DEVELOP)

release: BUILDTYPE = $(BT_RELEASE)

export BTYPE=$(BUILDTYPE)

# Directories
BUILDDIR		:=	build/
SRCDIR			:=	src/
SETUPDIR		:=	setup/
BUILDSUBDIR		:=	$(BUILDDIR)$(BTYPE)/
PATCHDIR		:=	Ninja/$(PATCHNAME)/
CONTENTDIR		:=	$(PATCHDIR)Content/

# Build software (added to PATH)
NSIS			:=	makensis
VDFS			:=	gothicvdfs

# TARGET
TARGET			:=	$(BUILDSUBDIR)$(PATCHNAME).vdf
SCRIPTVERSION	:=	$(SRCDIR)$(CONTENTDIR)version.d
VM				:=	$(SRCDIR)$(PATCHNAME).vm
TS				:=	Testsuite.src
TS_DEV			:=	TestsuiteDev.src
VMAUTO			:=	tmp.vm
SOURCES			:=	$(call rwildcard,$(subst /,,$(SRCDIR)),*.d *.src)
SETUP			:=	$(BUILDSUBDIR)$(PATCHNAME)-$(VERSION).exe
SETUPSCR		:=	$(SETUPDIR)g1mod.nsi
SETUPINC		:=	$(SETUPDIR)g1mod.nsh \
					$(SETUPDIR)setup.ini \
					LICENSE


# Phony rules
all : dev

dev : vdf

release :
	@$(MAKE) BUILDTYPE=release --no-print-directory vdf setup

setup : $(SETUP)

vdf : $(TARGET)

clean :
	$(RM) $(call FixPath,$(BUILDDIR)*)

remake : clean all

.PHONY : all clean remake vdf setup

# Remove temporary file VMAUTO after build
.INTERMEDIATE: $(VMAUTO)

# Prevent rebuild of VDF when building setup
.SECONDARY: $(TARGET)


# Build setup with the metadata
$(SETUP) : $(TARGET) $(SETUPSCR) $(SETUPINC) $(METADATA)
ifeq ($(BTYPE),$(BT_DEVELOP))
ifeq ($(DEVSETUP),0)
	$(info )
	@echo Setup of development build not intended. To create a setup of the development build anyway, run
	@echo     make DEVSETUP=1 setup && echo.
	exit 1
endif
endif
	$(NSIS) /X"SetCompressor /FINAL lzma" $(call FixPath,$(SETUPSCR))

# Build VDF
$(TARGET) : $(VMAUTO) $(SCRIPTVERSION) $(SOURCES)
	$(info Build $(BTYPE))
	@$(call mkdir,$(BUILDDIR))
	@$(call mkdir,$(BUILDDIR)$(BTYPE)/)
	@ATTRIB -a -h -r -s $(SRCDIR)* /S
ifeq ($(BTYPE),$(BT_RELEASE))
	$(call mv,$(SRCDIR)$(PATCHDIR)$(TS),$(TS_DEV))
	ECHO/> "$(call FixPath,$(SRCDIR)$(PATCHDIR)$(TS))"
endif
ifeq ($(VERBOSE),1)
	$(info Found resources:)
	$(foreach d,$(SOURCES),$(info - $d))
endif
	CD $(call FixPath,$(SRCDIR)) && $(VDFS) /B $(call FixPath,../$(VMAUTO))
ifeq ($(BTYPE),$(BT_RELEASE))
	$(RM) $(call FixPath,$(SRCDIR)$(PATCHDIR)$(TS))
	$(call mv,$(SRCDIR)$(PATCHDIR)$(TS_DEV),$(TS))
endif

# Auto-fill the VDFS VM script with the metadata
$(VMAUTO) : $(META) $(VM)
	@ECHO [BEGINVDF]>                                                             "$(call FixPath,$@)"
	@ECHO Comment=$(LONGNAME)  $(VBASE).$(VMAJOR).$(VMINOR)%%%%N$(WEBSITE)>>      "$(call FixPath,$@)"
	@ECHO BaseDir=.^\>>                                                           "$(call FixPath,$@)"
	@ECHO VDFName=.^\..^\$(call FixPath,$(TARGET))>>                              "$(call FixPath,$@)"
	@ECHO/>>                                                                      "$(call FixPath,$@)"
	@ECHO ;>>                                                                     "$(call FixPath,$@)"
	@TYPE $(call FixPath,$(VM))>>                                                 "$(call FixPath,$@)"

# Auto-generate version constant in Daedalus
$(SCRIPTVERSION): $(META)
	@ECHO /* This file is automatically generated. Do not edit */>                "$(call FixPath,$@)"
	@ECHO const int G1CP_Version = $(VBASE)*10000+$(VMAJOR)*100+$(VMINOR);>>      "$(call FixPath,$@)"
