blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/AmProsius/gothic-1-community-patch/discussions
    about: Please aks and answer general questions about the G1CP here.
