name: Initialize fix
description: Make an issue ready for fixing
inputs:
  issue_num:
    description: Issue number
    required: true
  token:
    description: Authentication token
    required: true
  shortname:
    description: Fix shortname
    required: true
  changelog_section:
    description: Changelog section
  changelog_en:
    description: English changelog
  changelog_de:
    description: German changelog
runs:
  using: node24
  main: 'dist/index.js'
