name: todo

on:
  pull_request:

jobs:
  fail-on-todo:
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOTWYN_ID }}
          private-key: ${{ secrets.BOTWYN_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}  # Make sure it is Botwyn who performs all actions

      - name: Fetch full history
        run: git fetch --unshallow || true

      - name: Check for occurrences of "TODO"
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          diff=$(git diff origin/${{ github.event.pull_request.base.ref }} --unified=0 -- 'src/Ninja/G1CP/**/*.d')

          todo_lines=$(echo "$diff" | grep '^+.*TODO' || true)
          if [[ "$todo_lines" ]]; then
            printf "\n\033[1;31mFound instances of 'TODO' in the added lines. Please remove them.\033[0m\n"
            echo "$diff" | while IFS= read -r line; do
              if [[ "$line" =~ ^\+.*TODO ]]; then
                printf "\033[1;33m%s\033[0m\n" "$line"
              elif [[ "$line" =~ ^\+\+\+ ]]; then
                echo "$line"
              fi
            done

            echo "### TODO
          Found instances of 'TODO' in the added lines. Please remove them.
          \`\`\`diff
          $todo_lines
          \`\`\`
          " >> $GITHUB_STEP_SUMMARY

            exit 1
          fi
