name: review

on:
  pull_request:
    types:
      - opened

jobs:
  review-todo:
    if: startsWith(github.head_ref, 'bug') && github.base_ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - name: Get token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          client-id: ${{ vars.BOTWYN_ID }}
          private-key: ${{ secrets.BOTWYN_KEY }}

      - name: Checkout
        uses: actions/checkout@v7
        with:
          token: ${{ steps.app-token.outputs.token }}  # Make sure it is Botwyn who performs all actions

      - name: Add review
        uses: ./.github/actions/reviewTodo
        id: review
        with:
          token: ${{ steps.app-token.outputs.token }}
          pr_num: ${{ github.event.number }}
