name: syntax

on:
  push:
    paths:
      - 'src/Ninja/G1CP/**/*.src'
      - 'src/Ninja/G1CP/**/*.d'

jobs:
  parsiphae:
    name: Run syntax check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BOTWYN_ID }}
          private-key: ${{ secrets.BOTWYN_KEY }}
      - uses: actions/checkout@v4
      - name: Check syntax
        uses: szapp/parsiphae-action@v1
        with:
          file: src/Ninja/G1CP/Content_G1.src
          token: ${{ steps.app-token.outputs.token }}
