name: syntax

on:
  push:
    paths:
      - 'src/Ninja/G1CP/**/*.src'
      - 'src/Ninja/G1CP/**/*.d'
  check_run:
    types: completed

permissions:
  checks: write
  actions: write

jobs:
  parsiphae:
    name: Run syntax check
    if: github.event_name != 'check_run' || github.event.check_run.external_id == format('{0}-0', github.workflow)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.BOTWYN_ID }}
          private-key: ${{ secrets.BOTWYN_KEY }}
      - uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}  # Make sure it is Botwyn who performs all actions
      - name: Check syntax
        uses: szapp/parsiphae-action@v1
        with:
          file: src/Ninja/G1CP/Content_G1.src
          token: ${{ steps.app-token.outputs.token }}
